architecture:
  name: Architecture
  description: Create architecture diagrams to visualize cloud and system infrastructure
  template: |
    architecture-beta
      group cloud_infra(cloud)[Cloud Infrastructure]
      
      service api_gateway(internet)[API Gateway] in cloud_infra
      service webserver(server)[Web Server] in cloud_infra
      service auth_service(server)[Auth Service] in cloud_infra
      service database(database)[Database] in cloud_infra
      service storage(disk)[Storage] in cloud_infra
      
      api_gateway:B -- T:webserver
      webserver:R -- L:auth_service
      auth_service:B -- T:database
      webserver:B -- T:database
      webserver:L -- R:storage
  syntax: |
    # Architecture Diagram Syntax
    
    # Start with architecture-beta
    architecture-beta
    
    # Groups
    group {group id}({icon name})[{title}]
    group {group id}({icon name})[{title}] in {parent id}
    
    # Services
    service {service id}({icon name})[{title}]
    service {service id}({icon name})[{title}] in {parent id}
    
    # Edges (must use L|R|T|B for directions)
    {serviceId}:L -- R:{serviceId}
    {serviceId}:T -- B:{serviceId}
    {serviceId}:R --> L:{serviceId}
    {serviceId}:B <-- T:{serviceId}
    
    # Junctions
    junction {junction id}
    junction {junction id} in {parent id}
    
    # Available icons: cloud, database, disk, internet, server
    # Can also use iconify.design icons with format "name:icon-name" 